"""empty message

Revision ID: 101f1af0e32
Revises: None
Create Date: 2015-09-24 21:26:11.307863

"""

# revision identifiers, used by Alembic.
revision = '101f1af0e32'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=64), nullable=False),
    sa.Column('last', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('age_group_1', sa.Boolean(), nullable=False),
    sa.Column('age_group_2', sa.Boolean(), nullable=False),
    sa.Column('age_group_3', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_age_group_1'), 'user', ['age_group_1'], unique=False)
    op.create_index(op.f('ix_user_age_group_2'), 'user', ['age_group_2'], unique=False)
    op.create_index(op.f('ix_user_age_group_3'), 'user', ['age_group_3'], unique=False)
    op.create_index(op.f('ix_user_confirmed'), 'user', ['confirmed'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first'), 'user', ['first'], unique=False)
    op.create_index(op.f('ix_user_last'), 'user', ['last'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last'), table_name='user')
    op.drop_index(op.f('ix_user_first'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_confirmed'), table_name='user')
    op.drop_index(op.f('ix_user_age_group_3'), table_name='user')
    op.drop_index(op.f('ix_user_age_group_2'), table_name='user')
    op.drop_index(op.f('ix_user_age_group_1'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
