"""empty message

Revision ID: 36ca1f3da54
Revises: 2cfd0589e8d
Create Date: 2015-11-13 18:09:14.029429

"""

# revision identifiers, used by Alembic.
revision = '36ca1f3da54'
down_revision = '2cfd0589e8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=64), nullable=False),
    sa.Column('last', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('age_group_1', sa.Boolean(), nullable=False),
    sa.Column('age_group_2', sa.Boolean(), nullable=False),
    sa.Column('age_group_3', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.CheckConstraint('age_group_1 or age_group_2 or age_group_3', name='age_group_selected'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_age_group_1'), ['age_group_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_age_group_2'), ['age_group_2'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_age_group_3'), ['age_group_3'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_confirmed'), ['confirmed'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_first'), ['first'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last'), ['last'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_last'))
        batch_op.drop_index(batch_op.f('ix_user_first'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_confirmed'))
        batch_op.drop_index(batch_op.f('ix_user_age_group_3'))
        batch_op.drop_index(batch_op.f('ix_user_age_group_2'))
        batch_op.drop_index(batch_op.f('ix_user_age_group_1'))

    op.drop_table('user')
    ### end Alembic commands ###
