"""create User table

Revision ID: 5374c571c70
Revises: None
Create Date: 2015-09-22 17:32:46.175774

"""

# revision identifiers, used by Alembic.
revision = '5374c571c70'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=64), nullable=False),
    sa.Column('last', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first'), 'user', ['first'], unique=False)
    op.create_index(op.f('ix_user_last'), 'user', ['last'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last'), table_name='user')
    op.drop_index(op.f('ix_user_first'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
